---
# Tasks on providers after AE-DIR tools installation

- name: "Create AE-DIR htdocs/ directory structure"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  with_items:
    - "{{ document_root }}"
    - "{{ document_root }}/reporting"

- name: "Copy non-template files to AE-DIR htdocs/"
  copy:
    src: "{{ role_path }}/files/"
    dest: "{{ document_root }}/"
    follow: no
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    directory_mode: u=rwx,g=rx,o=rx

- name: "Generate HTML pages in AE-DIR htdocs/"
  template:
    src: "{{ item }}.html.j2"
    dest: "{{ document_root }}/{{ item }}.html"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    directory_mode: u=rwx,g=rx,o=rx
  with_items: "{{ htdocs_templates }}"
